// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf4GdwTQwQx_9SiYGryQbiSiHNOqNO7BE',
    appId: '1:216710139863:web:d878da4476c2db199f0592',
    messagingSenderId: '216710139863',
    projectId: 'dolby-aa3a5',
    authDomain: 'dolby-aa3a5.firebaseapp.com',
    storageBucket: 'dolby-aa3a5.firebasestorage.app',
    measurementId: 'G-5PL48E6T10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe_jjH4nTe31q4j7mzvPRImMgn6PGYkcA',
    appId: '1:216710139863:android:1a4d9c41e39eb4ed9f0592',
    messagingSenderId: '216710139863',
    projectId: 'dolby-aa3a5',
    storageBucket: 'dolby-aa3a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUpkyHrIGjbKCxrpyguQaAjTjuUtBaaA',
    appId: '1:216710139863:ios:809ade114b609fd99f0592',
    messagingSenderId: '216710139863',
    projectId: 'dolby-aa3a5',
    storageBucket: 'dolby-aa3a5.firebasestorage.app',
    iosBundleId: 'com.taskdone.dolby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUpkyHrIGjbKCxrpyguQaAjTjuUtBaaA',
    appId: '1:216710139863:ios:809ade114b609fd99f0592',
    messagingSenderId: '216710139863',
    projectId: 'dolby-aa3a5',
    storageBucket: 'dolby-aa3a5.firebasestorage.app',
    iosBundleId: 'com.taskdone.dolby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf4GdwTQwQx_9SiYGryQbiSiHNOqNO7BE',
    appId: '1:216710139863:web:ab7280059d3a7f329f0592',
    messagingSenderId: '216710139863',
    projectId: 'dolby-aa3a5',
    authDomain: 'dolby-aa3a5.firebaseapp.com',
    storageBucket: 'dolby-aa3a5.firebasestorage.app',
    measurementId: 'G-Y8HBGRY78Z',
  );

}